version: "3.7"
services:
  SSCService:
    container_name: server_SSC_dev
    build:
      context: ..
    image: SSC_server_img
    hostname: "SSC01"
    ports:
    - 5151:5151
    volumes:
    - ./data:/opt
