version: "3.7"
services:
  SSCService:
    container_name: server_SSC_dev
    build:
      context: ..
    image: ssc_server_img
    hostname: "SSC01"
    ports:
    - 5152:5152
    volumes:
    - ./data/ssc:/var/app/data
